/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace FluxPriceFeed {
  export type ConfigStruct = {
    asset: PromiseOrValue<string>;
    source: PromiseOrValue<string>;
  };

  export type ConfigStructOutput = [string, string] & {
    asset: string;
    source: string;
  };
}

export interface FluxPriceFeedInterface extends utils.Interface {
  functions: {
    "TARGET_DIGITS()": FunctionFragment;
    "getAssetPrice(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "TARGET_DIGITS" | "getAssetPrice"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "TARGET_DIGITS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetPrice",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "TARGET_DIGITS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetPrice",
    data: BytesLike
  ): Result;

  events: {
    "AssetPriceFeedSourceUpdated(address,address)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "AssetPriceFeedSourceUpdated"
  ): EventFragment;
}

export interface AssetPriceFeedSourceUpdatedEventObject {
  asset: string;
  source: string;
}
export type AssetPriceFeedSourceUpdatedEvent = TypedEvent<
  [string, string],
  AssetPriceFeedSourceUpdatedEventObject
>;

export type AssetPriceFeedSourceUpdatedEventFilter =
  TypedEventFilter<AssetPriceFeedSourceUpdatedEvent>;

export interface FluxPriceFeed extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FluxPriceFeedInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    TARGET_DIGITS(overrides?: CallOverrides): Promise<[BigNumber]>;

    getAssetPrice(
      _asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  TARGET_DIGITS(overrides?: CallOverrides): Promise<BigNumber>;

  getAssetPrice(
    _asset: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    TARGET_DIGITS(overrides?: CallOverrides): Promise<BigNumber>;

    getAssetPrice(
      _asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "AssetPriceFeedSourceUpdated(address,address)"(
      asset?: PromiseOrValue<string> | null,
      source?: PromiseOrValue<string> | null
    ): AssetPriceFeedSourceUpdatedEventFilter;
    AssetPriceFeedSourceUpdated(
      asset?: PromiseOrValue<string> | null,
      source?: PromiseOrValue<string> | null
    ): AssetPriceFeedSourceUpdatedEventFilter;
  };

  estimateGas: {
    TARGET_DIGITS(overrides?: CallOverrides): Promise<BigNumber>;

    getAssetPrice(
      _asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    TARGET_DIGITS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAssetPrice(
      _asset: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
